// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbaKsd0nt2Erj62UuE8lOhL029TbHieic',
    appId: '1:25930876909:web:95cfc950b296ca0af309e4',
    messagingSenderId: '25930876909',
    projectId: 'pythonbrowser-23b14',
    authDomain: 'pythonbrowser-23b14.firebaseapp.com',
    storageBucket: 'pythonbrowser-23b14.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmmlWgXW_TB2hHU0lQ7Xv-jPoo9FsxuDE',
    appId: '1:25930876909:android:d6018a28cefe9057f309e4',
    messagingSenderId: '25930876909',
    projectId: 'pythonbrowser-23b14',
    storageBucket: 'pythonbrowser-23b14.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbaKsd0nt2Erj62UuE8lOhL029TbHieic',
    appId: '1:25930876909:web:084774b18b965862f309e4',
    messagingSenderId: '25930876909',
    projectId: 'pythonbrowser-23b14',
    authDomain: 'pythonbrowser-23b14.firebaseapp.com',
    storageBucket: 'pythonbrowser-23b14.firebasestorage.app',
  );
}
